### ISSUE TITLE
Provide support for boltlabs-release.toml file

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#642]
Provide support for boltlabs-release.toml file

We wish to have the the status and any api that returns the software version, return the version documented above. This information should also be logged to the application's main log file when the maestro/key-mgmt application starts up.

1. Create a new file in the key-mgmt repository _boltlabs-release.toml_
    ```toml
    [release]
    keymgmt=1.2.3+075.f8ada50.GA
    build-date=YYYYMMDDHHMM+TZ
    ```
2. The default values would be _develop_
3. At build creation time the build process will update the toml file with the appropriate values.

## API
1. Add the information from this toml file to the check_session endpoint in key-mgmt
